### PR TITLE
feat(font): add fusion pixel

### PR DESCRIPTION
**Pull request by OverflowCat**
[Fusion Pixel Font](https://fusion-pixel-font.takwolf.com/) is an open-source sans-serif pixel font designed to support Chinese, Japanese, and Korean (CJK) characters. It offers clear and sharp readability at 8, 10, and 12-pixel sizes.

The font has 3 pixel sizes, 2 styles (monospace and proportional), and 5 locales, resulting in a total of 30 combinations. Although I have added the locales using subsets, I am not entirely certain if they are functioning correctly (e.g., whether the family names are correctly assigned), as font files are renamed from different, separate locale-specific files.

## Fonts added

```sh
fusion-pixel-8px-monospaced
fusion-pixel-8px-proportional
fusion-pixel-10px-monospaced
fusion-pixel-10px-proportional
fusion-pixel-12px-monospaced
fusion-pixel-12px-proportional
```

They are added using a script. I didn't include it here; check [this branch](https://github.com/OverflowCat/font-files/blob/fusion/fonts/other/fusion.js). You need to run it using Bun.

### CODE REVIEW

**Review by ayuhito — CHANGES_REQUESTED** [review]
Thanks for your submission! Unfortunately, we do not support subsetting ([#730](https://github.com/fontsource/fontsource/issues/730)) with the custom packager. For now, that's only supported for Google Fonts. 

Would it be possible to have a one large file instead? I understand it would be extremely bloated, being a CJK font, but that's the only way we can really support this through our custom packager at the moment. Another way is getting this font approved by Google Fonts which will be the most usable format.

**Comment by OverflowCat** [comment]
In fact, the subsets here are not actually subsetting. Each individual subset contains the entire font (e.g., the other four contain Latin). For CJK, due to [Han unification](https://en.m.wikipedia.org/wiki/Han_unification) in Unicode, many characters that look slightly different in different locales are assigned to a single Unicode code point. Therefore, we cannot combine fonts from different locales. So the question is actually if users have the option to manually specify the subsets they wish to utilize.



My original plan was to create a font name for each locale, but that would result in 6 * 5 = 30 packages.

(Nevertheless, there is no need to worry about size - this is a pixel font, much smaller than typical CJK fonts.)

**Comment by ayuhito** [comment]
> My original plan was to create a font name for each locale, but that would result in 6 * 5 = 30 packages.

To my understanding, that is exactly what Google Fonts does.

- Noto Sans TC/Noto Sans SC/Noto Sans KR etc.
- IBM Plex Sans JP/IBM Plex Sans KR

And more.

I'm not against adding a large number of packages. Google doesn't seem to be either looking at the newest fonts added to Fontsource:

image

But I wonder if all 30 packages are necessary? If you have any ideas to reduce that, that will be great to hear about. But if they are all uniquely different, I think it is okay to introduce these packages separately.

**Comment by ayuhito** [comment]
We could also remove the individual latin subset entirely, and only ship `4 * 6 = 24` packages as one way.

**Comment by OverflowCat** [comment]
Since the glyphs for Latin and symbols differ between mono and proportional fonts, and 8/10/12px sizes can indeed be considered as separate fonts, I don't think there's a way to further reduce the count. I will modify my build script to generate 24 packages.

8px
10px
12px

Before that, I'd like to confirm that fontsource should be using fontface to import our fonts, so the family name I specified in the metadata is irrelevant to the font files (woff and woff2, if they have built-in family names). Is it correct?

**Comment by ayuhito** [comment]
You need to give each package metadata a different family name, as it will then generate a different `@font-face` name which will take precedence over any built-in family names.

There are times we regenerate the CSS in this repository using only the metadata, thus the metadata has to be accurate.

**Review by OverflowCat — COMMENTED** [review]
Now ready for review :-)

**Review by ayuhito — CHANGES_REQUESTED** [review]
Sorry for the delay! I was on holiday. Thank you for making the changes.

The changes look functionally fine but I think we should remain consistent with Google for the naming. e.g. instead of `Fusion Pixel 10px Monospaced ja`, it should be `Fusion Pixel 10px Monospaced JP` or instead of `Fusion Pixel 10px Monospaced ko`, it should be `Fusion Pixel 10px Monospaced KR`. This would be much less confusing for end users.

You can check on the Fontsource website, but Google uses JP, KR, TC, SC for the shortened names.

**Comment by OverflowCat** [comment]
The test likely failed due to the absence of `-latin-` in the font files, for which I will make adjustments later.

> Google uses JP, KR, TC, SC for the shortened names

The naming follows the font file's family name, which I checked using FontForge. If changing the names does not cause any issues, then I will proceed with that.

Btw _Fusion Kai_ in the repository (not by the same author) uses G / T / J, following font author's naming. Fusion Pixel doesn't explicitly call their variants "Fusion Pixel zh-hant", "Fusion Pixel ja", etc. in their website so I think renaming is fine (?)

**Comment by ayuhito** [comment]
I think we should change the names for consistency. We're already modifying the fonts by subsetting it separately like this, so it should be fine.

**Review by ayuhito — APPROVED** [review]
Thank you so much for your patience. Everything looks good to me!!

**Pull request merged**
